### ISSUE TITLE
CORS issue if jot-server is installed on another server.

### ISSUE THREAD

**Issue by vinodchandel** [unaio/jot-client-una#132]
CORS issue is occurring if jot-server is installed on another server and UNA app on another server. Also in documentation there is no detail if we use other server for jot-server.

**Comment by AlexeyUna** [comment]
Jot Server can be installed on another server and one Jot Server instance can be used for many different domains simultaneously.

You may see CORS problem in browser console in case if Jot Server was installed on the server with not valid certificate or in Jot Server's config was defined wrong paths to certificate files. Also when port on the server with Jot Server is closed for external connections.

Check please if the port with running Jot Server is available for connect with command:
**telnet yourdomainname.com port**

**Comment by vinodchandel** [comment]
Ok,  Thank you for information :)
