### ISSUE TITLE
"Exceeded max files to send in one" message error

### ISSUE THREAD

**Issue by AlexeyUna** [unaio/jot-client-una#207]
https://una.io/m/messenger/archive/255297

**Comment by AlexeyUna** [comment]
I can not reproduce the problem anymore.

**Comment by AlexTr** [comment]
It's still there:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/3324866/196831470-44eedda6-3d32-4239-90af-613df765d27c.png">

Create several chats, send send messages with attachments, in different chats

**Comment by AlexeyUna** [comment]
Error can be reproduced only in Chrome and files should be added only using drag and drop.
