### ISSUE TITLE
Una Version: 12.1.1-DEV1 

### ISSUE THREAD

**Issue by olariuromeo** [unaio/jot-client-una#248]
Trayng to install in una: The module is not compatible with your version of UNA  (Una Version: 12.1.1-DEV1 Messenger Version: 12.0.7).  where can be download messenger with a version compatible with UNA 12?

**Comment by olariuromeo** [comment]
There are no tags for previous versions, https://una.io/u/alexey  has published several links for diferent versions but they all lead to the same page where the latest version is https://una.io/view-product/messenger
Not everyone uses the same version of UNA, where can we download previous versions? I need MESSENGER version compatible with UNA 12

**Comment by AlexeyUna** [comment]
Hello!

I've answered on this questions here https://una.io/cmts-view/182sebh?sys=bx_forum&cmt_id=44759
