### ISSUE TITLE
Messenger improvements

### ISSUE THREAD

**Issue by romanlesnikov** [unaio/jot-client-una#71]
1. Delete button is not work 
![image](https://user-images.githubusercontent.com/12896257/56360571-c31b4b00-61ed-11e9-8c7d-595828c99fa2.png)
2. Need colorize talks witch have a new messages or another way to make it more unusual
3. No way to determinate who is online, who not.
4. Causes the difficulty of getting into this menu. Solution: shows it below / above the points, it will solve the problem with the over event
![image](https://user-images.githubusercontent.com/12896257/56361044-04602a80-61ef-11e9-87e0-9eb25acacd83.png)
5. When posting a lot of links it's look like as below, 
![image](https://user-images.githubusercontent.com/12896257/56361086-248fe980-61ef-11e9-86da-5521227f36fd.png)
It would be nice to have a simple view of the display of links (without a embed), because the text becomes difficult to read. (Add setting for user or like in slack, ability to remove embed view for each link)
6. Wll usefull transform ```text``` to another style as in Slack

**Comment by AlexeyUna** [comment]
The most part of the issues are fixed.
Item 6 will be spread to separate ticket.
