### ISSUE TITLE
Messenger stops working correctly after some time

### ISSUE THREAD

**Issue by AlexTr** [unaio/jot-client-una#81]
New messages don't show in messenger. Also number of new messages stop updating. It makes messenger using very difficult. I have to reload page with messenger every hour or so to see new messages and new counters.

It can be reproduced when page with messenger is open for long time, also the problem is in desktop app.

**Comment by AlexeyUna** [comment]
Seems like this problem may occur because of some js errors and uncatch throws.

![image](https://user-images.githubusercontent.com/22319431/66678123-d75b7480-ec73-11e9-9ce8-969e0fba0687.png)
